# Generated by Django 4.0.4 on 2022-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userreport_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wing',
            field=models.CharField(blank=True, choices=[ ('INFORMATION TECHNOLOGY','INFORMATION TECHNOLOGY',),
                                                         ('CIVIL ENGINEERING','CIVIL ENGINEERING'),
                                                         ('TEXTILE ENGINEERING','TEXTILE ENGINEERING'),
                                                         ('TRAVEL`S AND TOURISM', 'TRAVEL`S AND TOURISM'),
                                                         ('PACKAGING ENGINEERING','PACKAGING ENGINEERING'),
                                                         ('MECHANICAL ENGINEERING','MECHANICAL ENGINEERING'),
                                                         ('ELECTRICAL ENGINEERING','ELECTRICAL ENGINEERING'),
                                                         ('AUTOMOBILE ENGINEERING','AUTOMOBILE ENGINEERING'),
                                                         ('METALLURGICAL ENGINEERING','METALLURGICAL ENGINEERING'),
                                                         ('MINING AND MINE SURVEYING', 'MINING AND MINE SURVEYING'),
                                                         ('ETX','ETX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reason',
            field=models.CharField(choices=[('SPAM', 'SPAM'), ('INAPPROPRIATE', 'INAPPROPRIATE')], max_length=50),
        ),
    ]
